In [6]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)
def load_array(data_arrays, batch_size, is_train = True):
    dataset = data.TensorDataset(features, labels)
    return data.DataLoader(dataset, batch_size, shuffle = is_train)
batch_size = 10
data_iter = load_array((features,labels), batch_size)

In [7]:
next(iter(data_iter))

[tensor([[-0.8423, -0.0242],
         [ 0.7635,  1.7642],
         [ 1.4627, -0.2954],
         [-0.6035, -0.0860],
         [-0.4742, -0.0220],
         [-0.4491, -0.8970],
         [ 0.2459,  1.4837],
         [ 0.0194, -0.7363],
         [-0.2928, -2.2684],
         [-0.1356,  0.9585]]),
 tensor([[ 2.5838],
         [-0.2534],
         [ 8.1368],
         [ 3.3028],
         [ 3.3322],
         [ 6.3428],
         [-0.3295],
         [ 6.7394],
         [11.3367],
         [ 0.6981]])]

In [8]:
from torch import nn
net = nn.Sequential(nn.Linear(2, 1))
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [9]:
loss = nn.MSELoss()

In [10]:
trainer = torch.optim.SGD(net.parameters(), lr = 0.03)
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l: f}')

epoch 1, loss  0.000163
epoch 2, loss  0.000097
epoch 3, loss  0.000097


In [13]:
net[0].weight.data, net[0].bias.data

(tensor([[ 2.0001, -3.4002]]), tensor([4.2005]))